FROM node:16

ENV APP_HOME /usr/src/app
WORKDIR $APP_HOME
ADD ./package.json .
ADD ./yarn.lock .
RUN yarn install --frozen-lockfile

ADD . .

ENV NODE_ENV production
RUN yarn install

RUN yarn build

EXPOSE 1337

CMD ["yarn", "start"]