apiVersion: v1
kind: Service
metadata:
  name: strapi-service
  labels:
    app: strapi
spec:
  ports:
  - name: https       ##This port is where ingress connects
    port: 443
    targetPort: 1337
  selector:
    app: strapi 
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi 
  labels:
    app: strapi 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strapi 
  template:
    metadata:
      labels:
        app: strapi 
    spec:
      containers:
      - name: strapi 
        image: arislankareem/strapi:latest
        ports:
        - name: http
          containerPort: 1337
        envFrom:
        - secretRef:
            name: strapi-prod
        volumeMounts:
        - name: certs
          mountPath: "/etc/certs"
          readOnly: true
      volumes:
      - name: certs
        secret:
          secretName: auth-tls-secret  
      

            